### ISSUE TITLE
[Document][THANHHUONG] - Fix wikis images error

### ISSUE THREAD

**Issue by nhanntdl** [thanhhuong2020/thanhhuong2020.github.io#1]
Dear, @LieuTran287 

The image in our wiki has been displayed error

Please help me fix it

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will receive this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work in [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
Dear @LieuTran287,

**Commit** lại nha em

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Ok anh.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
> Dear @nhanntdl ,
> 
> Ok anh.
> 
> Thanks,
> Lieu

xem làm ở file nào thì link từng file cho anh luôn nè. để anh còn biết file nào chưa file nào rồi anh review cho dễ nha em

**Comment by LieuTran287** [comment]
> > Dear @nhanntdl ,
> > Ok anh.
> > Thanks,
> > Lieu
> 
> xem làm ở file nào thì link từng file cho anh luôn nè. để anh còn biết file nào chưa file nào rồi anh review cho dễ nha em

Dạ vâng

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I have fixed this work.
The links that I have fixed are [link1](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-t%E1%BA%A1o-wiki), [link2](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-T%E1%BA%A0O-M%E1%BB%98T-ISSUES), [link3](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-SOURCE-TREE)
Please check this work with the links above.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
> Dear @nhanntdl ,
> 
> I have fixed this work.
> The links that I have fixed are [link1](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-t%E1%BA%A1o-wiki), [link2](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-T%E1%BA%A0O-M%E1%BB%98T-ISSUES), [link3](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-SOURCE-TREE)
> Please check this work with the links above.
> 
> Thanks,
> Lieu

ok em. xong rồi ha.. anh close task luôn
