### ISSUE TITLE
[Document][THANHHUONG] - #3 - Radio box

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#10]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã làm xong cái task này rồi.
Anh kiểm tra lại giúp em nha.
Task trong đường : [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-RADIO-BOX)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok good job
ngâm cứu thêm em nhé

**Comment by LieuTran287** [comment]
> ok good job
> ngâm cứu thêm em nhé

Dạ vâng
