### ISSUE TITLE
[THANHHUONG][wiki] - Tạo wiki về source tree

### ISSUE THREAD

**Issue by nhanntdl** [thanhhuong2020/thanhhuong2020.github.io#2]
Dear, @LieuTran287 

Hãy viết wiki về cách sử dụng source tree

1. Cài đặt môi trường

2. Clone

3. Checkout branch

Please help me do this

Thanks and Best Regards
YourName

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work in [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-SOURCE-TREE)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
Dear @thanhhuong2020 [BSE]

Please translate this issue for me into English

Thanks & Best Regards
TrungNhan
