### ISSUE TITLE
[Document][THANHHUONG] - #3 - Thanh điều hướng

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#4]

**Comment by nhanntdl** [comment]
Dear @LieuTran287 

em chỉ cần làm wiki đơn giản. vừa đủ thôi nè em

chỉ cần 1 cái ảnh sản phẩm và code là được rồi nha

làm lại em nhé

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
> Dear @LieuTran287
> 
> em chỉ cần làm wiki đơn giản. vừa đủ thôi nè em
> 
> chỉ cần 1 cái ảnh sản phẩm và code là được rồi nha
> 
> làm lại em nhé
> 
> Thanks
> TrungNhan

Dạ anh, em sẽ sửa lại.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Anh ơi em sửa lại cái này rồi anh xem thử được k anh.
Trong wiki: [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-THANH-%C4%90I%E1%BB%80U-H%C6%AF%E1%BB%9ANG)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok good job
