### ISSUE TITLE
[Document][THANHHUONG] - #3 - Nút bấm liên kết

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#5]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã sửa cho cái task này rồi.
Anh kiểm tra giúp em nha.
Task trong wiki: [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-N%C3%9AT-B%E1%BA%A4M-LI%C3%8AN-K%E1%BA%BET)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok good job
