### ISSUE TITLE
[Document][THANHHUONG] - #3 - Nút bấm nộp dữ liệu

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#6]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Anh ơi em làm xong cái task này rồi.
Anh kiểm tra lại giúp em nha.
Link task nè anh: https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-N%C3%9AT-B%E1%BA%A4M-N%E1%BB%98P-D%E1%BB%AE-LI%E1%BB%86U

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok. good job
