### ISSUE TITLE
[Document][THANHHUONG] - #3 - Textbox

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#7]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã sửa cho cái task này rồi.
Anh kiểm tra giúp em nha.
Task trong wiki: https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-TEXTBOX

Thanks,
Lieu

**Comment by nhanntdl** [comment]
good job
