### ISSUE TITLE
[Translate][THANHHUONG] - Translate wiki "Home"

### ISSUE THREAD

**Issue by nhanntdl** [thanhhuong2020/thanhhuong2020.github.io#8]
Dear @thanhhuong2020 [BSE],

Please translate [Home](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki) for me into English

Thanks & Best Regards
TrungNhan

**Comment by thanhhuong2020** [comment]
Dear @nhanntdl ,

This wiki has been translated, please check back and close this task.

Thanks & Best Regards
BSE

**Comment by nhanntdl** [comment]
Dear @thanhhuong2020 [BSE],

OK

Thanks & Best Regards
TrungNhan
