### ISSUE TITLE
[Document][THANHHUONG] - #3 - Combobox

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#8]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã làm xong cái task này rồi.
Anh kiểm tra lại giúp em nha.
Task trong [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-COMBOBOX)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
OK.. tạm
