### ISSUE TITLE
[Document][THANHHUONG] - #3 - Check box

### ISSUE THREAD

**Issue by LieuTran287** [thanhhuong2020/thanhhuong2020.github.io#9]

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had complete this work.
Please check my work in [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%C3%A0i-li%E1%BB%87u-v%E1%BB%81-c%C3%A1ch-tri%E1%BB%83n-khai-code-html-v%C3%A0-css)

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã làm xong cái task này rồi.
Anh kiểm tra lại giúp em nha.
Task trong đường link: [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%E1%BA%A0O-CHECKBOX)

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok. good job

tuy nhiên xem lại code có vài chỗ hơi dưa thừa nhé em

**Comment by LieuTran287** [comment]
> ok. good job
> 
> tuy nhiên xem lại code có vài chỗ hơi dưa thừa nhé em

Dạ vâng
