### ISSUE TITLE
[Document][THANHHUONG] - Tạo wiki về Github Project

### ISSUE THREAD

**Issue by nhanntdl** [thanhhuong2020/thanhhuong2020.github.io#9]
Dear, @all,

Anh cần một cái wiki về Github Project,
Nội dung trọng tâm:
- Cách điều hướng task
- Cách xem task cá nhân

Please help me to documentation for this

Thanks and Best Regards
TrungNhan

**Comment by thanhhuong2020** [comment]
Dear anh @nhanntdl , 

Để em làm cho nà :) 

Thanks,
BSE

**Comment by thanhhuong2020** [comment]
OK em

**Comment by nhanntdl** [comment]
> Dear anh @nhanntdl ,
> 
> Để em làm cho nà :)
> 
> Thanks,
> BSE

OK em

**Comment by thanhhuong2020** [comment]
Dear anh @nhanntdl ,

Em làm xong rồi nè sếp oi,
Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%ACA-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊

Thanks,
BSE

**Comment by thanhhuong2020** [comment]
> Dear anh @nhanntdl ,
> 
> Em làm xong rồi nè sếp oi,
> Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%ACA-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
> 
> Thanks,
> BSE

OK em

**Comment by nhanntdl** [comment]
> Dear anh @nhanntdl ,
> 
> Em làm xong rồi nè sếp oi,
> Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%ACA-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
> 
> Thanks,
> BSE

OK em

**Comment by nhanntdl** [comment]
Dear @thanhhuong2020 [BSE]

Lỗi nè em
![image](https://user-images.githubusercontent.com/61504492/75604765-ece01680-5b0e-11ea-9506-345fa8694337.png)
Check lại cho kỹ nha em.

Thanks and Best Regards
TrungNhan

**Comment by thanhhuong2020** [comment]
Dear anh @nhanntdl ,

Em sửa lại rồi nè sếp oi,
Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%ACA-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊

Thanks,
BSE

**Comment by nhanntdl** [comment]
> Dear anh @nhanntdl ,
> 
> Em sửa lại rồi nè sếp oi,
> Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%ACA-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
> 
> Thanks,
> BSE

OK

**Comment by nhanntdl** [comment]
Dear @thanhhuong2020 [BSE]

Còn lỗi nè em
![image](https://user-images.githubusercontent.com/52454131/75604865-cd95b900-5b0f-11ea-8123-f6df1d5ade1d.png)
Check cho kỹ đi cô nương của tui

Thanks and Best Regards
TrungNhan

**Comment by thanhhuong2020** [comment]
Dear anh @nhanntdl ,

Em sửa lại rồi nè sếp oi,
Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
Soi quá à 😭

Thanks,
BSE

**Comment by nhanntdl** [comment]
> Dear anh @nhanntdl ,
> 
> Em sửa lại rồi nè sếp oi,
> Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
> Soi quá à 😭
> 
> Thanks,
> BSE

OK rồi đó. Xem tự tạo task dịch luôn đi.

**Comment by thanhhuong2020** [comment]
> > Dear anh @nhanntdl ,
> > Em sửa lại rồi nè sếp oi,
> > Kiểm tra [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/C%C3%81CH-S%E1%BB%AC-D%E1%BB%A4NG-GITHUB-PROJECT) này giúp em nhé 😊
> > Soi quá à 😭
> > Thanks,
> > BSE
> 
> OK rồi đó. Xem tự tạo task dịch luôn đi.

Ryoukai sếp!!! 👮‍♀️
